config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show, :edit]

  get 'portfolio/:id', :to => 'portfolios#show', :as => 'portfolio_show'
  get 'portfolio/:id/edit', :to => 'portfolios#edit', :as => 'portfolio_edit'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  get 'about', :to => 'pages#about'
  get 'contact', :to => 'pages#contact'

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, :presence => true
  validates :body, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged

  enum status: { :draft => 0, :published => 1 }
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates :title, :presence => true
  validates :subtitle, :presence => true
  validates :body, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :get_blog_post, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, :notice => 'Post status was successfully updated!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_blog_post
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /home
  def home
  end

  # GET /about
  def about
  end

  # GET /contact
  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :get_portfolio_item, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  def index
    @portfolio_items = Portfolio.all
  end

  # GET /portfolios/1
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio_item = Portfolio.new
  end

  # POST /portfolios
  def create
    @portfolio_item = Portfolio.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, :notice => 'Portfolio item was successfully created' }
      else
        format.html { render 'new' }
      end
    end
  end

  # GET /portfolios/1/edit
  def edit
  end

  # PATCH /portfolios/1
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to portfolio_show_path(@portfolio_item), :notice => 'Portfolio item was successfully updated' }
      else
        format.html { render 'edit' }
      end
    end
  end

  # DESTROY /portfolios/1
  def destroy
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully removed!' }
    end
  end

  private
    def portfolio_item_params
      params.require(:portfolio)
        .permit(:title, :subtitle, :body)
    end

    def get_portfolio_item
      @portfolio_item = Portfolio.friendly.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.slim
= form_with model: @blog, local: true do |form|

  - if blog.errors.any?
    
    div#error_explanation
      h2
        => pluralize(@blog.errors.count, 'Error')
        | prohibited this post from being saved

      ul
        - @blog.errors.full_messages.each do |msg|
          li = msg

  div.field
    = form.label :title
    = form.text_field :title

  div.field
    = form.label :body
    = form.text_area :body

  div.actions
    = form.submit

app/views/blogs/edit.slim
h1
  | Editing Post

= render 'form', blog: @blog

= link_to 'Show', @blog
=> link_to 'Back', blogs_path

app/views/blogs/index.slim
p#notice
  = notice

h1
  | Blogs

table
  thead
    tr
      th
        | Title
      th
        | Body
      th colspan="4"

  tbody
    - @blogs.each do |blog|
      tr
        td = blog.title
        td = blog.body
        td = link_to blog.status, toggle_status_blog_path(blog)
        td = link_to 'Show', blog
        td = link_to 'Edit', edit_blog_path(blog)
        td = link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' }

br

=<> link_to 'New Blog', new_blog_path
=<> link_to 'Home', root_path
=<> link_to 'Portfolio', portfolios_path

app/views/blogs/new.slim
h1
  | New Post

= render 'form', blog: @blog

= link_to 'Back', blogs_path

app/views/blogs/show.slim
p#notice
  = notice

p
  strong
    | Title:
  = @blog.title

p
  strong
    | Body:
  = @blog.body

=> link_to 'Edit', edit_blog_path(@blog);
=< link_to 'Back', blogs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatILearnedToday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.slim
h1
  | About page

= link_to 'Back', root_path

app/views/pages/contact.slim
h1
  | Contact Me

= link_to 'Back', root_path

app/views/pages/home.slim
h1
  | Home page

=> link_to 'About', about_path
=< link_to 'Contact Me', contact_path
=<> link_to 'Blog', blogs_path
=<> link_to 'Portfolio', portfolios_path

app/views/portfolios/_form.slim
= form_with :model => @portfolio_item, :local => true do |form|

  div.field
    = form.label :title
    br
    = form.text_field :title
  br

  div.field
    = form.label :subtitle
    br
    = form.text_field :subtitle
  br

  div.field
    = form.label :body
    br
    = form.text_area :body
  br

  div.field
    = form.submit
  br

= link_to 'Back', portfolios_path

app/views/portfolios/_navbar.slim
ul
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li = link_to 'Contact', contact_path
  li = link_to 'Blog', blogs_path
  li = link_to 'Portfolio', portfolios_path

app/views/portfolios/_notice.slim
div#portfolios_notice
  = notice

app/views/portfolios/edit.slim
= render 'navbar'
= render 'notice' if notice

hr

div
  h1
    | Editing
    =<> @portfolio_item.title  
    | Portfolio Item

  div
    = image_tag @portfolio_item.main_image
  
  br

= render 'form'

app/views/portfolios/index.slim
div
  = render 'navbar'
  br
  = render 'notice' if notice

hr

h1
  | Portfolios Index Page

div
  = link_to 'Create Portfolio-Item', new_portfolio_path

div
  - @portfolio_items.each do |portfolio_item|
    
    div
      p = link_to portfolio_item.title, portfolio_show_path(portfolio_item)
      p = portfolio_item.subtitle
      p = portfolio_item.body
      p = image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?

      div
        span
          =<> link_to 'Show', portfolio_show_path(portfolio_item)
          =<> link_to 'Edit', portfolio_edit_path(portfolio_item)
          =<> link_to 'Delete', portfolio_path(portfolio_item), method: 'delete', data: { :confirm => 'Are you sure?' }
    hr

app/views/portfolios/new.slim
= render 'navbar'

hr

h1
  | Create a new portfolio item

= render 'form'

app/views/portfolios/show.slim
= render 'navbar'
= render 'notice' if notice

hr

div
  h1
    | Title:
    =< @portfolio_item.title

  h2
    | Sub-title:
    =< @portfolio_item.subtitle

  div
    = image_tag @portfolio_item.main_image

    h3
      | Body:
      =< @portfolio_item.body

=<> link_to 'Back', portfolios_path
=<> link_to 'Edit', portfolio_edit_path(@portfolio_item)
=<> link_to 'Delete', portfolio_path(@portfolio_item), :method => 'delete', data: { :confirm => 'Are you sure?' }